name: Alistair pipeline

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  build:
    name: Build repo
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'yarn'

    - name: Install yarn packages
      run: yarn install
    - name: Run unit tests
      run: yarn test
    - name: Build
      run: yarn build
    - name: Run e2e tests
      run: yarn test:e2e
